version: '3'
volumes:
  game_downloads:
    driver: local
services:
  gamedownloader:
    build:
      context: .
      dockerfile: Containerfile
    name: gamedownloader
    hostname: gamedownloader
    tty: true
    stdio: true
    restart: no
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'game_downloads:/mnt:rw'
